const fs = require('fs');

const core = [
  {
    key: 'flying',
    name_en: 'Flying',
    name_zh: '飞行',
    keywords_en: ['freedom', 'ambition', 'escape', 'control'],
    keywords_zh: ['自由', '理想', '逃离', '掌控'],
    psych_en:
      'Flying dreams often reflect a wish for freedom, confidence, or rising above pressure. Losing control mid-flight can mirror anxiety about performance or responsibility.',
    psych_zh:
      '梦见飞行通常象征自由感、自信或想从压力中抽离；若飞行失控，常反映对能力、责任或表现的焦虑。',
    culture_en:
      'Across cultures, flight is linked with transcendence and spiritual ascent; modern stories also frame it as empowerment and self-determination.',
    culture_zh:
      '在多种文化中，飞行与超越、升华相关；在现代叙事里，也常代表力量感与自我主导。'
  },
  {
    key: 'falling',
    name_en: 'Falling',
    name_zh: '坠落',
    keywords_en: ['loss', 'uncertainty', 'failure', 'letting go'],
    keywords_zh: ['失控', '不确定', '失败', '放手'],
    psych_en:
      'Falling can symbolize loss of control, insecurity, or fear of failure. It may appear during life transitions, deadlines, or relationship uncertainty.',
    psych_zh:
      '坠落常象征失控、不安全感或对失败的担忧；在转折期、压力期或关系不稳定时更常出现。',
    culture_en:
      'Many traditions treat falling as a warning to slow down and regain balance; in modern pop culture it is a classic anxiety motif.',
    culture_zh:
      '一些传统将坠落视作提醒：放慢脚步、重新找回平衡；在现代语境中，它也是典型的焦虑意象。'
  },
  {
    key: 'water',
    name_en: 'Water',
    name_zh: '水',
    keywords_en: ['emotion', 'intuition', 'cleansing', 'depth'],
    keywords_zh: ['情绪', '直觉', '净化', '深层'],
    psych_en:
      'Water often points to emotion and intuition. Calm water may suggest regulation and clarity; flooding can signal overwhelm or unprocessed feelings.',
    psych_zh:
      '水常指向情绪与直觉：平静的水代表稳定与清晰；洪水或淹没则可能暗示情绪过载或未被处理的感受。',
    culture_en:
      'Water is widely linked to purification and rebirth. Rivers, oceans, and rain carry distinct meanings tied to journey, vastness, and renewal.',
    culture_zh:
      '水在许多文化中与净化、重生相关；河流、海洋、雨水又分别带有旅程、广阔与更新等象征。'
  },
  {
    key: 'snake',
    name_en: 'Snake',
    name_zh: '蛇',
    keywords_en: ['instinct', 'threat', 'healing', 'transformation'],
    keywords_zh: ['本能', '威胁', '疗愈', '蜕变'],
    psych_en:
      'Snakes can represent primal instinct, anxiety, or a boundary being crossed. They may also symbolize renewal when connected with shedding skin and change.',
    psych_zh:
      '蛇可代表原始本能、焦虑或界限被侵犯；也可能象征更新与变化（如蜕皮带来的重生意涵）。',
    culture_en:
      'In some cultures snakes are omens or tricksters; in others they are healing symbols (medicine) and guardians of wisdom.',
    culture_zh:
      '在一些文化里蛇象征危险、诱惑或诡计；在另一些传统中，它也与疗愈（医药）与智慧守护相关。'
  },
  {
    key: 'teeth',
    name_en: 'Teeth',
    name_zh: '牙齿',
    keywords_en: ['appearance', 'anxiety', 'communication', 'aging'],
    keywords_zh: ['外貌', '焦虑', '表达', '衰老'],
    psych_en:
      'Teeth dreams often cluster around stress, self-image, and communication. Losing teeth can mirror fear of embarrassment, aging, or saying the wrong thing.',
    psych_zh:
      '牙齿相关的梦常与压力、自我形象与表达有关；掉牙可能对应对尴尬、衰老或“说错话”的担忧。',
    culture_en:
      'Some folklore frames teeth loss as an omen; modern interpretations more often treat it as stress and body-image processing.',
    culture_zh:
      '民俗里有时把掉牙当作征兆；现代解读更常将其视为压力与身体/形象焦虑的反映。'
  },
  {
    key: 'chase',
    name_en: 'Being Chased',
    name_zh: '被追赶',
    keywords_en: ['avoidance', 'fear', 'pressure', 'conflict'],
    keywords_zh: ['逃避', '恐惧', '压力', '冲突'],
    psych_en:
      'Chase dreams can signal avoidance: a feeling, task, or conflict you do not want to face. Noticing who/what chases you can clarify the theme.',
    psych_zh:
      '被追赶常意味着逃避：你可能在回避某种情绪、任务或冲突；追赶者是谁/是什么，往往能提示核心议题。',
    culture_en:
      'Across storytelling traditions, pursuit scenes externalize internal struggle. The dream may invite you to turn and address what is following you.',
    culture_zh:
      '在叙事传统中，追逐常是内在冲突的外化；梦也许在邀请你回头面对一直“跟着你”的东西。'
  }
];

const keys = [
  'death',
  'baby',
  'pregnancy',
  'wedding',
  'ex',
  'breakup',
  'naked',
  'exam',
  'school',
  'teacher',
  'late',
  'missed_train',
  'car',
  'crash',
  'driving',
  'lost',
  'house',
  'room',
  'door',
  'window',
  'stairs',
  'elevator',
  'bridge',
  'tunnel',
  'forest',
  'mountain',
  'ocean',
  'river',
  'rain',
  'storm',
  'fire',
  'smoke',
  'earthquake',
  'flood',
  'ice',
  'snow',
  'wind',
  'lightning',
  'sun',
  'moon',
  'stars',
  'planet',
  'space',
  'alien',
  'monster',
  'ghost',
  'zombie',
  'vampire',
  'spider',
  'insects',
  'bees',
  'ants',
  'dog',
  'cat',
  'horse',
  'lion',
  'tiger',
  'bear',
  'wolf',
  'bird',
  'owl',
  'crow',
  'fish',
  'shark',
  'whale',
  'dolphin',
  'turtle',
  'frog',
  'butterfly',
  'mouse',
  'rat',
  'pig',
  'cow',
  'sheep',
  'goat',
  'deer',
  'rabbit',
  'dragon',
  'phoenix',
  'mirror',
  'phone',
  'message',
  'email',
  'computer',
  'internet',
  'camera',
  'money',
  'coins',
  'gold',
  'jewelry',
  'gift',
  'stealing',
  'police',
  'prison',
  'gun',
  'knife',
  'blood',
  'injury',
  'hospital',
  'doctor',
  'surgery',
  'vomit',
  'toilet',
  'bathroom',
  'shower',
  'hair',
  'cutting_hair',
  'clothes',
  'shoes',
  'running',
  'swimming',
  'drowning',
  'falling_teeth',
  'broken_teeth',
  'missing_teeth',
  'kiss',
  'sex',
  'cheating',
  'family',
  'mother',
  'father',
  'sister',
  'brother',
  'child',
  'friend',
  'enemy',
  'boss',
  'work',
  'promotion',
  'failure',
  'success',
  'public_speaking',
  'stage',
  'music',
  'dance',
  'painting',
  'book',
  'library',
  'church',
  'temple',
  'mosque',
  'ritual',
  'funeral',
  'birth',
  'garden',
  'flowers',
  'rose',
  'lotus',
  'tree',
  'apple',
  'banana',
  'grapes',
  'bread',
  'cake',
  'chocolate',
  'coffee',
  'tea',
  'salt',
  'sugar',
  'spice',
  'mirror_break',
  'broken_glass',
  'glass',
  'cleaning',
  'laundry',
  'trash',
  'ring',
  'key',
  'lock',
  'map',
  'compass',
  'clock',
  'time',
  'train',
  'airplane',
  'airport',
  'ship',
  'boat',
  'bicycle',
  'motorcycle',
  'road',
  'traffic',
  'crowd',
  'party',
  'war',
  'soldier',
  'escape',
  'hiding',
  'searching',
  'lost_child',
  'missing_person',
  'attack',
  'falling_building',
  'collapse',
  'height',
  'cliff',
  'pit',
  'maze',
  'labyrinth',
  'desert',
  'island',
  'beach',
  'city',
  'village',
  'market',
  'restaurant',
  'kitchen',
  'bed',
  'sleep_paralysis',
  'lucid',
  'apocalypse',
  'end_of_world',
  'phone_call',
  'texting',
  'doorbell',
  'music_box',
  'mask',
  'shadow',
  'twins',
  'triplets',
  'graduation',
  'interview',
  'resume',
  'lottery',
  'gambling',
  'taxes',
  'debt',
  'stormy_sea',
  'calm_sea',
  'deep_water',
  'dirty_water',
  'clear_water',
  'tsunami',
  'volcano',
  'candle',
  'lantern',
  'electricity',
  'power_outage',
  'mirror_face',
  'unknown_house',
  'old_house',
  'new_house',
  'basement',
  'attic',
  'roof',
  'bath',
  'swamp',
  'mud',
  'sand',
  'bridge_broken',
  'falling_from_height',
  'parachute',
  'wings',
  'swarm',
  'bites',
  'sting',
  'poison',
  'medicine',
  'therapy',
  'meditation',
  'yoga',
  'prayer',
  'angel',
  'demon',
  'witch',
  'spell',
  'curse',
  'luck',
  'numbers',
  'colors',
  'blue',
  'red',
  'white',
  'black',
  'green',
  'yellow',
  'purple',
  'silver',
  'wound',
  'scar',
  'tattoo',
  'piercing',
  'tears',
  'laughing',
  'crying',
  'screaming',
  'silence',
  'voice',
  'singing',
  'teeth_crumbling',
  'toothache',
  'tongue',
  'eyes',
  'blind',
  'glasses',
  'skin',
  'spinning',
  'floating',
  'trapped',
  'locked_room',
  'lost_phone',
  'lost_wallet',
  'wallet',
  'passport',
  'visa',
  'border',
  'customs',
  'hotel',
  'eating',
  'fasting',
  'hunger',
  'thirst',
  'portal',
  'teleport',
  'time_travel',
  'future',
  'past',
  'childhood',
  'old_friend',
  'proposal',
  'divorce',
  'arguments',
  'reconciliation',
  'forgiveness',
  'jealousy',
  'betrayal',
  'secret',
  'stairs_endless',
  'elevator_stuck',
  'broken_elevator',
  'lost_keys',
  'finding_money',
  'robbery',
  'earth',
  'dirt',
  'seed',
  'harvest',
  'moonlight',
  'starlight',
  'sunrise',
  'sunset',
  'eclipse',
  'comet',
  'shooting_star',
  'constellation',
  'nebula',
  'galaxy'
];

const uniqKeys = Array.from(new Set([...core.map((x) => x.key), ...keys]));

function titleCase(s) {
  return s.replace(/_/g, ' ').replace(/\b\w/g, (m) => m.toUpperCase());
}

const zhMap = {
  death: '死亡',
  baby: '婴儿',
  pregnancy: '怀孕',
  wedding: '婚礼',
  naked: '裸露',
  exam: '考试',
  school: '学校',
  car: '汽车',
  crash: '车祸',
  driving: '驾驶',
  lost: '迷路',
  house: '房子',
  door: '门',
  window: '窗',
  stairs: '楼梯',
  elevator: '电梯',
  bridge: '桥',
  tunnel: '隧道',
  forest: '森林',
  mountain: '山',
  ocean: '海洋',
  river: '河流',
  rain: '雨',
  storm: '风暴',
  fire: '火',
  earthquake: '地震',
  snow: '雪',
  moon: '月亮',
  stars: '星星',
  ghost: '鬼',
  spider: '蜘蛛',
  dog: '狗',
  cat: '猫',
  money: '钱',
  hospital: '医院',
  doctor: '医生',
  bathroom: '厕所',
  shower: '淋浴',
  shoes: '鞋',
  running: '奔跑',
  swimming: '游泳',
  drowning: '溺水',
  kiss: '亲吻',
  cheating: '出轨',
  family: '家庭',
  mother: '母亲',
  father: '父亲',
  friend: '朋友',
  boss: '老板',
  work: '工作',
  success: '成功',
  failure: '失败',
  interview: '面试',
  lottery: '彩票',
  debt: '债务',
  key: '钥匙',
  lock: '锁',
  clock: '时钟'
};

function template(key) {
  const en = titleCase(key);
  const zh = zhMap[key] || en;
  const kwEn = key.split(/[_\s]+/).filter(Boolean);

  const psych_en =
    'This symbol often reflects emotions and situations you are processing in waking life. Notice the setting, your body sensations, and whether you feel safe or pressured.';
  const psych_zh =
    '这个意象通常反映你在清醒生活中正在处理的情绪与处境。留意梦中的场景、身体感受，以及你是安全还是被逼迫。';
  const culture_en =
    'Across cultures, "' + en + '" can carry layered meanings shaped by stories, beliefs, and personal experience. Your associations matter most.';
  const culture_zh =
    '在不同文化中，“' + zh + '”常有多层含义，受故事、信仰与个人经历影响。你自己的联想最关键。';

  return {
    key,
    name_en: en,
    name_zh: zh,
    keywords_en: Array.from(new Set([key, ...kwEn])).slice(0, 10),
    keywords_zh: Array.from(new Set([zh])).slice(0, 10),
    psych_en,
    psych_zh,
    culture_en,
    culture_zh
  };
}

const byKey = new Map();
for (const c of core) byKey.set(c.key, c);
for (const k of uniqKeys) {
  if (!byKey.has(k)) byKey.set(k, template(k));
}

const out = Array.from(byKey.values());
if (out.length < 210) throw new Error('Too few symbols: ' + out.length);

fs.mkdirSync('/home/msdn/dreamoracle/data', { recursive: true });
fs.writeFileSync('/home/msdn/dreamoracle/data/symbols.json', JSON.stringify(out, null, 2));
console.log('symbols:', out.length);
